Model Facade
filipkauffeldt/oopp-grupp22 pull request #57
Opened 2023-11-27 14:07 UTC by filipkauffeldt

# Model Facade

Created a class that will act as a facade for the model. Should be used by the controller

Closes #48 
Closes #50

2023-11-27 14:26 UTC, Oskmey requested changes

2023-11-27 14:34 UTC, Pontus-Wikstrom approved these changes
Fix with tests and the comments, otherwise LGTM

2023-11-28 12:36 UTC, filipkauffeldt commented on crocket/src/main/java/com/crocket/Level1.java
>          if (height != tilemap.length) {
Removed method instead

2023-11-28 12:37 UTC, Oskmey approved these changes

2023-11-28 12:37 UTC, merged